import { type ColumnDef } from "@tanstack/react-table"
import type { SleepRecord } from "@/lib/types"
import "@/lib/table-types"
import {
  formatDateTime,
  formatDuration,
  formatPercentage,
  formatBoolean,
  formatInteger,
  formatDecimal,
} from "@/lib/formatters"

export const sleepColumns: ColumnDef<SleepRecord, unknown>[] = [
  {
    id: "id",
    accessorKey: "id",
    header: "ID",
    meta: { defaultVisible: false },
  },
  {
    id: "cycleId",
    accessorKey: "cycleId",
    header: "Cycle ID",
    meta: { defaultVisible: false },
  },
  {
    id: "cycleDate",
    header: "Cycle",
    accessorKey: "cycleId",
    cell: ({ getValue, table }) => {
      const cycleId = getValue() as number
      const cycleLookup = (table.options.meta as Record<string, unknown> | undefined)?.cycleLookup as Map<number, string> | undefined
      return cycleLookup?.get(cycleId) ?? String(cycleId)
    },
    meta: { defaultVisible: true },
  },
  {
    id: "start",
    accessorKey: "start",
    header: "Start",
    cell: ({ getValue }) => formatDateTime(getValue() as string),
    meta: { defaultVisible: true },
  },
  {
    id: "end",
    accessorKey: "end",
    header: "End",
    cell: ({ getValue }) => formatDateTime(getValue() as string),
    meta: { defaultVisible: true },
  },
  {
    id: "timezoneOffset",
    accessorKey: "timezoneOffset",
    header: "Timezone",
    meta: { defaultVisible: false },
  },
  {
    id: "isNap",
    accessorKey: "isNap",
    header: "Nap",
    cell: ({ getValue }) => formatBoolean(getValue() as boolean | null),
    meta: { defaultVisible: true },
  },
  {
    id: "scoreState",
    accessorKey: "scoreState",
    header: "Score State",
    meta: { defaultVisible: false },
  },
  {
    id: "createdAt",
    accessorKey: "createdAt",
    header: "Created",
    cell: ({ getValue }) => formatDateTime(getValue() as string),
    meta: { defaultVisible: false },
  },
  {
    id: "updatedAt",
    accessorKey: "updatedAt",
    header: "Updated",
    cell: ({ getValue }) => formatDateTime(getValue() as string),
    meta: { defaultVisible: false },
  },
  {
    id: "totalInBedMs",
    accessorKey: "totalInBedMs",
    header: "Duration",
    cell: ({ getValue }) => formatDuration(getValue() as number | null),
    meta: { defaultVisible: true, align: "right", unit: "hrs" },
  },
  {
    id: "totalAwakeMs",
    accessorKey: "totalAwakeMs",
    header: "Awake",
    cell: ({ getValue }) => formatDuration(getValue() as number | null),
    meta: { defaultVisible: true, align: "right", unit: "hrs" },
  },
  {
    id: "totalNoDataMs",
    accessorKey: "totalNoDataMs",
    header: "No Data",
    cell: ({ getValue }) => formatDuration(getValue() as number | null),
    meta: { defaultVisible: true, align: "right", unit: "hrs" },
  },
  {
    id: "totalLightSleepMs",
    accessorKey: "totalLightSleepMs",
    header: "Light",
    cell: ({ getValue }) => formatDuration(getValue() as number | null),
    meta: { defaultVisible: true, align: "right", unit: "hrs" },
  },
  {
    id: "totalDeepSleepMs",
    accessorKey: "totalDeepSleepMs",
    header: "Deep",
    cell: ({ getValue }) => formatDuration(getValue() as number | null),
    meta: { defaultVisible: true, align: "right", unit: "hrs" },
  },
  {
    id: "totalRemSleepMs",
    accessorKey: "totalRemSleepMs",
    header: "REM",
    cell: ({ getValue }) => formatDuration(getValue() as number | null),
    meta: { defaultVisible: true, align: "right", unit: "hrs" },
  },
  {
    id: "sleepCycleCount",
    accessorKey: "sleepCycleCount",
    header: "Sleep Cycles",
    cell: ({ getValue }) => formatInteger(getValue() as number | null),
    meta: { defaultVisible: true, align: "right" },
  },
  {
    id: "disturbanceCount",
    accessorKey: "disturbanceCount",
    header: "Disturbances",
    cell: ({ getValue }) => formatInteger(getValue() as number | null),
    meta: { defaultVisible: true, align: "right" },
  },
  {
    id: "sleepConsistencyPct",
    accessorKey: "sleepConsistencyPct",
    header: "Consistency",
    cell: ({ getValue }) => formatPercentage(getValue() as number | null),
    meta: { defaultVisible: true, align: "right" },
  },
  {
    id: "sleepPerformancePct",
    accessorKey: "sleepPerformancePct",
    header: "Performance",
    cell: ({ getValue }) => formatPercentage(getValue() as number | null),
    meta: { defaultVisible: true, align: "right" },
  },
  {
    id: "sleepEfficiencyPct",
    accessorKey: "sleepEfficiencyPct",
    header: "Efficiency",
    cell: ({ getValue }) => formatPercentage(getValue() as number | null),
    meta: { defaultVisible: true, align: "right" },
  },
  {
    id: "respiratoryRate",
    accessorKey: "respiratoryRate",
    header: "Resp. Rate",
    cell: ({ getValue }) => formatDecimal(getValue() as number | null),
    meta: { defaultVisible: true, align: "right", unit: "brpm" },
  },
  {
    id: "sleepNeededBaselineMs",
    accessorKey: "sleepNeededBaselineMs",
    header: "Baseline Need",
    cell: ({ getValue }) => formatDuration(getValue() as number | null),
    meta: { defaultVisible: true, align: "right", unit: "hrs" },
  },
  {
    id: "sleepNeededDebtMs",
    accessorKey: "sleepNeededDebtMs",
    header: "Sleep Debt",
    cell: ({ getValue }) => formatDuration(getValue() as number | null),
    meta: { defaultVisible: true, align: "right", unit: "hrs" },
  },
  {
    id: "sleepNeededStrainMs",
    accessorKey: "sleepNeededStrainMs",
    header: "Strain Need",
    cell: ({ getValue }) => formatDuration(getValue() as number | null),
    meta: { defaultVisible: true, align: "right", unit: "hrs" },
  },
  {
    id: "sleepNeededNapMs",
    accessorKey: "sleepNeededNapMs",
    header: "Nap Reduction",
    cell: ({ getValue }) => formatDuration(getValue() as number | null),
    meta: { defaultVisible: true, align: "right", unit: "hrs" },
  },
]
